### ISSUE TITLE
Authorize button disabled

### ISSUE THREAD

**Issue by NatsuOnFire** [dotronglong/dart-github-sign-in#6]
I implemented the plugin but the Authorize button on the GitHub page is disabled. I can only canceled.
Do you have any idea why the button does not activate?

Maybe you need to enable javascript in the WebView in `github_sign_in_page.dart`, it is disabled by default

I used version 0.0.5-dev.1
Flutter 2.5.1
Tested on an android emulator and on a real android phone

**Comment by dotronglong** [comment]
Published 0.0.5-dev.2
