### ISSUE TITLE
firebase_webview_plugin not supported

### ISSUE THREAD

**Issue by harshkumarkhatri** [dotronglong/dart-github-sign-in#9]
As I am trying to run the app using the package, I am getting this error
![image](https://user-images.githubusercontent.com/42743629/138550754-d523a726-c739-4e38-a945-fe36935f29d9.png)

Package version:
![image](https://user-images.githubusercontent.com/42743629/138550775-113af3ea-cc40-4a2b-84ce-e35fa749ff1e.png)

Flutter version - 2.5.1

Is the package no more supporting the GitHub sign-in in flutter apps?

**Comment by dotronglong** [comment]
It looks like you have invalid redirect url to me and please check if you configured your github oauth app correctly with redirect url.
